#!/bin/sh

#set -o errexit
#set -o pipefail
#set -o nounset

until cd /app
do
    echo "Waiting for server volume..."
done

until ./manage.py migrate
do
    echo "Waiting for db to be ready..."
    sleep 2
done

#python /app/manage.py collectstatic --noinput
gunicorn config.wsgi --bind 0.0.0.0:8000 --workers 3
